version: '3.3'

services:

  cdn:
    image: cdn
    build: cdn
    ports:
      - 80:80

  footer:
    image: footer
    build: frag-footer
    environment:
      - PUBLIC_URL=http://localhost:3000
    env_file:
      - .env
    ports:
      - 3000:3000
    depends_on:
      - cdn
    volumes:
      - ./frag-footer:/app
      - /app/node_modules

  header:
    image: header
    build: frag-header
    environment:
      - PUBLIC_URL=http://localhost:3001
    env_file:
      - .env
    ports:
      - 3001:3000
    depends_on:
      - cdn
    volumes:
      - ./frag-header:/app
      - /app/node_modules

  frag-one:
    image: frag-one
    build: frag-one
    environment:
      - PUBLIC_URL=http://localhost:3002
    env_file:
      - .env
    ports:
      - 3002:3000
    depends_on:
      - cdn
    volumes:
      - ./frag-one:/app
      - /app/node_modules

  frag-two:
    image: frag-two
    build: frag-two
    environment:
      - PUBLIC_URL=http://localhost:3003
    env_file:
      - .env
    ports:
      - 3003:3000
    depends_on:
      - cdn
    volumes:
      - ./frag-two:/app
      - /app/node_modules

  page:
    image: page
    build: page
    env_file:
      - .env
    ports:
      - 8080
    volumes:
      - ./page:/app
      - /app/node_modules
    depends_on:
      - header
      - footer
      - frag-one
      - frag-two
